[project]
name = "milo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Palash Jain", email = "palash.jain.cw@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
milo = "milo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
